## Import Requirements
#### if libraries are not available please install them locally using(pip install scikit-learn)

In [137]:
import numpy as np
import pandas as pd
import mlflow
import mlflow.sklearn
import optuna
import joblib
import time
import re
import nltk


from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline 
from sklearn.metrics import classification_report, f1_score, confusion_matrix
from optuna.integration.mlflow import MLflowCallback


from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler, MinMaxScaler, MaxAbsScaler
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,f1_score

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

import os
os.environ["LOKY_MAX_CPU_COUNT"] = "4" 

import warnings
warnings.filterwarnings("ignore")

## Data cleaning (EDA)

In [138]:
df=pd.read_csv("data.csv")

In [139]:
df

,Reviewer Name,Review Title,Place of Review,Up Votes,Down Votes,Month,Review text,Ratings
0,Kamal Suresh,Nice product,"Certified Buyer, Chirakkal",889.0,64.0,Feb 2021,"Nice product, good quality, but price is now r...",4
1,Flipkart Customer,Don't waste your money,"Certified Buyer, Hyderabad",109.0,6.0,Feb 2021,They didn't supplied Yonex Mavis 350. Outside ...,1
2,A. S. Raja Srinivasan,Did not meet expectations,"Certified Buyer, Dharmapuri",42.0,3.0,Apr 2021,Worst product. Damaged shuttlecocks packed in ...,1
3,Suresh Narayanasamy,Fair,"Certified Buyer, Chennai",25.0,1.0,NaN,"Quite O. K. , but nowadays the quality of the...",3
4,ASHIK P A,Over priced,NaN,147.0,24.0,Apr 2016,Over pricedJust â?¹620 ..from retailer.I didn'...,1
...,...,...,...,...,...,...,...,...
8513,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
8514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
8515,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
8516,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
8517,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4

In [140]:
df.isnull().sum()/len(df)*100

Reviewer Name      0.117398
Review Title       0.117398
Place of Review    0.586992
Up Votes           0.117398
Down Votes         0.117398
Month              5.459028
Review text        0.093919
Ratings            0.000000
dtype: float64

In [141]:
df = df.drop(columns=['Reviewer Name','Place of Review','Month'])
df = df.dropna(subset=['Review text'])
initial_count = len(df)
df = df.drop_duplicates(subset=['Review text'], keep='first')
print(f"Removed {initial_count - len(df)} duplicate reviews.")
df['Review Title'] = df['Review Title'].fillna('')
df['Up Votes'] = df['Up Votes'].fillna(0)
df['Down Votes'] = df['Down Votes'].fillna(0)
df['full_review'] = df['Review Title'] + ' ' + df['Review text']
df = df.reset_index(drop=True)
df.isnull().sum()

Removed 3527 duplicate reviews.

Review Title    0
Up Votes        0
Down Votes      0
Review text     0
Ratings         0
full_review     0
dtype: int64

In [142]:
df.shape

(4983, 6)

In [143]:
df = df[df['Ratings'] != 3]
df['sentiment'] = df['Ratings'].apply(lambda x: 1 if x >= 4 else 0)
df = df.drop(columns=['Ratings'])
df = df.reset_index(drop=True)

In [144]:

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

stop_words = set(stopwords.words('english'))
negations = {'not', 'no', 'nor', 'never'}
stop_words = stop_words - negations
lemmatizer = WordNetLemmatizer()
def clean_text(text):
    text = text.lower()
    text = re.sub(r'http\S+|www\S+', '', text)
    text = re.sub(r'[^a-z\s]', '', text)
    tokens = [
        lemmatizer.lemmatize(word)
        for word in text.split()
        if word not in stop_words and len(word) > 2]
    return ' '.join(tokens)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [145]:
df['clean_review'] = df['full_review'].apply(clean_text)
df[['full_review', 'clean_review']].sample(5)

,full_review,clean_review
2011,Fair SatisfactionREAD MORE,fair satisfactionread
2360,Delightful Nice 👌👌👌👌READ MORE,delightful nice read
430,Very Good Super 👍👍👍READ MORE,good super read
4585,Costly on flipkart You will get this product a...,costly flipkart get product around max retaile...
401,Terrific purchase Great product. Timely delive...,terrific purchase great product timely deliver...

## Train–Test Split

In [146]:
X = df['clean_review']
y = df['sentiment']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

##  CV strategy

In [147]:

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

##  MODEL 1: Logistic Regression

In [148]:
def objective_logreg(trial):
    tfidf_max_features = trial.suggest_int("max_features", 5000, 20000)
    ngram_range = trial.suggest_categorical("ngram_range", [(1,1), (1,2)])
    C = trial.suggest_float("C", 0.1, 10.0, log=True)

    pipeline = ImbPipeline([
        ("tfidf", TfidfVectorizer(max_features=tfidf_max_features,ngram_range=ngram_range,sublinear_tf=True,
            min_df=3)),
        ("smote", SMOTE(random_state=42)), 
        ("clf", LogisticRegression(C=C, max_iter=1000))])

    scores = cross_val_score(pipeline, X_train, y_train, cv=cv, scoring="f1_macro")
    return scores.mean()

## Optuna-Run

In [149]:
study_logreg = optuna.create_study(direction="maximize")
study_logreg.optimize(objective_logreg, n_trials=30)

logreg_f1 = study_logreg.best_value
logreg_params = study_logreg.best_params

[I 2026-02-02 08:25:15,062] A new study created in memory with name: no-name-1ae6d005-f952-4178-a34d-72124a4addd6
[I 2026-02-02 08:25:15,796] Trial 0 finished with value: 0.8459317998787498 and parameters: {'max_features': 16145, 'ngram_range': (1, 2), 'C': 0.49727515530759264}. Best is trial 0 with value: 0.8459317998787498.
[I 2026-02-02 08:25:16,244] Trial 1 finished with value: 0.8436679155864084 and parameters: {'max_features': 7716, 'ngram_range': (1, 2), 'C': 0.3234786065641758}. Best is trial 0 with value: 0.8459317998787498.
[I 2026-02-02 08:25:16,554] Trial 2 finished with value: 0.8429650178310799 and parameters: {'max_features': 10302, 'ngram_range': (1, 1), 'C': 1.0308703500865772}. Best is trial 0 with value: 0.8459317998787498.
[I 2026-02-02 08:25:17,145] Trial 3 finished with value: 0.8460810832455211 and parameters: {'max_features': 19431, 'ngram_range': (1, 2), 'C': 6.947769584309274}. Best is trial 3 with value: 0.8460810832455211.
[I 2026-02-02 08:25:17,481] Trial 4 finished with value: 0.8362004126372314 and parameters: {'max_features': 16496, 'ngram_range': (1, 1), 'C': 7.979224708876809}. Best is trial 3 with value: 0.8460810832455211.
[I 2026-02-02 08:25:17,951] Trial 5 finished with value: 0.8521717684523121 and parameters: {'max_features': 12613, 'ngram_range': (1, 2), 'C': 2.8415224037144178}. Best is trial 5 with value: 0.8521717684523121.
[I 2026-02-02 08:25:18,402] Trial 6 finished with value: 0.8494319537546747 and parameters: {'max_features': 12208, 'ngram_range': (1, 2), 'C': 1.0271410144554545}. Best is trial 5 with value: 0.8521717684523121.
[I 2026-02-02 08:25:18,673] Trial 7 finished with value: 0.8426769038332574 and parameters: {'max_features': 19229, 'ngram_range': (1, 1), 'C': 0.35797884361588717}. Best is trial 5 with value: 0.8521717684523121.
[I 2026-02-02 08:25:18,955] Trial 8 finished with value: 0.8423272681073757 and parameters: {'max_features': 11890, 'ngram_range': (1, 1), 'C': 0.6970058648240371}. Best is trial 5 with value: 0.8521717684523121.
[I 2026-02-02 08:25:19,405] Trial 9 finished with value: 0.8514806781967309 and parameters: {'max_features': 19186, 'ngram_range': (1, 2), 'C': 1.4237924850872374}. Best is trial 5 with value: 0.8521717684523121.
[I 2026-02-02 08:25:19,846] Trial 10 finished with value: 0.8339821967227377 and parameters: {'max_features': 6493, 'ngram_range': (1, 2), 'C': 0.11138529929396361}. Best is trial 5 with value: 0.8521717684523121.
[I 2026-02-02 08:25:20,316] Trial 11 finished with value: 0.8519657777587687 and parameters: {'max_features': 15485, 'ngram_range': (1, 2), 'C': 2.504758199294411}. Best is trial 5 with value: 0.8521717684523121.
[I 2026-02-02 08:25:20,813] Trial 12 finished with value: 0.8517152816240545 and parameters: {'max_features': 15346, 'ngram_range': (1, 2), 'C': 2.81686439418326}. Best is trial 5 with value: 0.8521717684523121.
[I 2026-02-02 08:25:21,303] Trial 13 finished with value: 0.8525522497458915 and parameters: {'max_features': 14694, 'ngram_range': (1, 2), 'C': 3.3132449192441147}. Best is trial 13 with value: 0.8525522497458915.
[I 2026-02-02 08:25:21,770] Trial 14 finished with value: 0.8532368264505447 and parameters: {'max_features': 9939, 'ngram_range': (1, 2), 'C': 3.5379550504526582}. Best is trial 14 with value: 0.8532368264505447.
[I 2026-02-02 08:25:22,260] Trial 15 finished with value: 0.853373367943133 and parameters: {'max_features': 9649, 'ngram_range': (1, 2), 'C': 3.6685845193568754}. Best is trial 15 with value: 0.853373367943133.
[I 2026-02-02 08:25:22,714] Trial 16 finished with value: 0.8500727306478104 and parameters: {'max_features': 8487, 'ngram_range': (1, 2), 'C': 4.942057594972858}. Best is trial 15 with value: 0.853373367943133.
[I 2026-02-02 08:25:23,330] Trial 17 finished with value: 0.8545903648819149 and parameters: {'max_features': 5489, 'ngram_range': (1, 2), 'C': 1.7983657492193463}. Best is trial 17 with value: 0.8545903648819149.
[I 2026-02-02 08:25:23,658] Trial 18 finished with value: 0.843667284552404 and parameters: {'max_features': 5128, 'ngram_range': (1, 1), 'C': 1.2299431164799839}. Best is trial 17 with value: 0.8545903648819149.
[I 2026-02-02 08:25:24,111] Trial 19 finished with value: 0.8393748946936661 and parameters: {'max_features': 5014, 'ngram_range': (1, 2), 'C': 0.16998316130112986}. Best is trial 17 with value: 0.8545903648819149.
[I 2026-02-02 08:25:24,571] Trial 20 finished with value: 0.8549255275653236 and parameters: {'max_features': 8266, 'ngram_range': (1, 2), 'C': 1.8275972483514173}. Best is trial 20 with value: 0.8549255275653236.
[I 2026-02-02 08:25:25,031] Trial 21 finished with value: 0.8545903648819149 and parameters: {'max_features': 7373, 'ngram_range': (1, 2), 'C': 1.8046150610036182}. Best is trial 20 with value: 0.8549255275653236.
[I 2026-02-02 08:25:25,500] Trial 22 finished with value: 0.8545705334280459 and parameters: {'max_features': 6994, 'ngram_range': (1, 2), 'C': 1.8439894002157025}. Best is trial 20 with value: 0.8549255275653236.
[I 2026-02-02 08:25:26,163] Trial 23 finished with value: 0.8542349120564037 and parameters: {'max_features': 6125, 'ngram_range': (1, 2), 'C': 1.8601054612737669}. Best is trial 20 with value: 0.8549255275653236.
[I 2026-02-02 08:25:26,859] Trial 24 finished with value: 0.8481783189049068 and parameters: {'max_features': 8542, 'ngram_range': (1, 2), 'C': 0.6832488445733575}. Best is trial 20 with value: 0.8549255275653236.
[I 2026-02-02 08:25:27,424] Trial 25 finished with value: 0.8549255275653236 and parameters: {'max_features': 7571, 'ngram_range': (1, 2), 'C': 1.8202581082444405}. Best is trial 20 with value: 0.8549255275653236.
[I 2026-02-02 08:25:27,744] Trial 26 finished with value: 0.8366662762883195 and parameters: {'max_features': 8667, 'ngram_range': (1, 1), 'C': 5.241405942800891}. Best is trial 20 with value: 0.8549255275653236.
[I 2026-02-02 08:25:28,201] Trial 27 finished with value: 0.848057210768749 and parameters: {'max_features': 5787, 'ngram_range': (1, 2), 'C': 0.7317407149202153}. Best is trial 20 with value: 0.8549255275653236.
[I 2026-02-02 08:25:28,667] Trial 28 finished with value: 0.8532342008693699 and parameters: {'max_features': 10948, 'ngram_range': (1, 2), 'C': 2.3043577573336997}. Best is trial 20 with value: 0.8549255275653236.
[I 2026-02-02 08:25:29,116] Trial 29 finished with value: 0.8464311184014335 and parameters: {'max_features': 7974, 'ngram_range': (1, 2), 'C': 0.5211481065224781}. Best is trial 20 with value: 0.8549255275653236.

## MODEL 2: Linear SVM

In [150]:
def objective_svm(trial):
    tfidf_max_features = trial.suggest_int("max_features", 5000, 20000)
    ngram_range = trial.suggest_categorical("ngram_range", [(1,1), (1,2)])
    C = trial.suggest_float("C", 1e-3, 10, log=True)
    pipeline = ImbPipeline([
        ("tfidf", TfidfVectorizer(max_features=tfidf_max_features,ngram_range=ngram_range,sublinear_tf=True, min_df=3)),
        ("smote", SMOTE(random_state=42)), # Generates synthetic negative reviews
        ("clf", LinearSVC(C=C, max_iter=2000)) ])

    scores = cross_val_score(pipeline,X_train,y_train,cv=cv,scoring="f1_macro")

    return scores.mean()

In [151]:
study_svm = optuna.create_study(direction="maximize")
study_svm.optimize(objective_svm, n_trials=30)

svm_f1 = study_svm.best_value
svm_params = study_svm.best_params

[I 2026-02-02 08:25:53,079] A new study created in memory with name: no-name-7ea2a4e4-edbd-4ebf-92e2-975ce0e4e134
[I 2026-02-02 08:25:53,566] Trial 0 finished with value: 0.8543459374393543 and parameters: {'max_features': 11534, 'ngram_range': (1, 2), 'C': 0.08756844701321756}. Best is trial 0 with value: 0.8543459374393543.
[I 2026-02-02 08:25:54,023] Trial 1 finished with value: 0.8342699978477345 and parameters: {'max_features': 5834, 'ngram_range': (1, 2), 'C': 1.7691798132604661}. Best is trial 0 with value: 0.8543459374393543.
[I 2026-02-02 08:25:54,297] Trial 2 finished with value: 0.8451662252836663 and parameters: {'max_features': 18445, 'ngram_range': (1, 1), 'C': 0.05400104682370516}. Best is trial 0 with value: 0.8543459374393543.
[I 2026-02-02 08:25:54,699] Trial 3 finished with value: 0.8288804390823759 and parameters: {'max_features': 15248, 'ngram_range': (1, 2), 'C': 0.004497480987244084}. Best is trial 0 with value: 0.8543459374393543.
[I 2026-02-02 08:25:55,161] Trial 4 finished with value: 0.8114294122757892 and parameters: {'max_features': 13733, 'ngram_range': (1, 2), 'C': 6.311275069825784}. Best is trial 0 with value: 0.8543459374393543.
[I 2026-02-02 08:25:55,422] Trial 5 finished with value: 0.8436212934834035 and parameters: {'max_features': 15410, 'ngram_range': (1, 1), 'C': 0.04900442553411869}. Best is trial 0 with value: 0.8543459374393543.
[I 2026-02-02 08:25:55,813] Trial 6 finished with value: 0.8252583199663321 and parameters: {'max_features': 15702, 'ngram_range': (1, 2), 'C': 0.0018257577603549937}. Best is trial 0 with value: 0.8543459374393543.
[I 2026-02-02 08:25:56,129] Trial 7 finished with value: 0.8077420601082002 and parameters: {'max_features': 7154, 'ngram_range': (1, 1), 'C': 9.518330835588257}. Best is trial 0 with value: 0.8543459374393543.
[I 2026-02-02 08:25:56,482] Trial 8 finished with value: 0.8427657267127617 and parameters: {'max_features': 14670, 'ngram_range': (1, 1), 'C': 0.017810952151929405}. Best is trial 0 with value: 0.8543459374393543.
[I 2026-02-02 08:25:56,793] Trial 9 finished with value: 0.8243907805627053 and parameters: {'max_features': 18285, 'ngram_range': (1, 1), 'C': 1.9539092333983192}. Best is trial 0 with value: 0.8543459374393543.
[I 2026-02-02 08:25:57,248] Trial 10 finished with value: 0.8508856860250373 and parameters: {'max_features': 9682, 'ngram_range': (1, 2), 'C': 0.3184069311937853}. Best is trial 0 with value: 0.8543459374393543.
[I 2026-02-02 08:25:57,719] Trial 11 finished with value: 0.8518935654174312 and parameters: {'max_features': 9994, 'ngram_range': (1, 2), 'C': 0.29192085727881273}. Best is trial 0 with value: 0.8543459374393543.
[I 2026-02-02 08:25:58,153] Trial 12 finished with value: 0.8507365832582758 and parameters: {'max_features': 10018, 'ngram_range': (1, 2), 'C': 0.3236190501908772}. Best is trial 0 with value: 0.8543459374393543.
[I 2026-02-02 08:25:58,597] Trial 13 finished with value: 0.8510108265893839 and parameters: {'max_features': 11210, 'ngram_range': (1, 2), 'C': 0.26754977571538796}. Best is trial 0 with value: 0.8543459374393543.
[I 2026-02-02 08:25:59,002] Trial 14 finished with value: 0.833166905328023 and parameters: {'max_features': 8410, 'ngram_range': (1, 2), 'C': 0.010607688963843991}. Best is trial 0 with value: 0.8543459374393543.
[I 2026-02-02 08:25:59,485] Trial 15 finished with value: 0.8406815222141726 and parameters: {'max_features': 12094, 'ngram_range': (1, 2), 'C': 0.9493759057849825}. Best is trial 0 with value: 0.8543459374393543.
[I 2026-02-02 08:25:59,928] Trial 16 finished with value: 0.8549322285131817 and parameters: {'max_features': 12964, 'ngram_range': (1, 2), 'C': 0.15581681778282555}. Best is trial 16 with value: 0.8549322285131817.
[I 2026-02-02 08:26:00,371] Trial 17 finished with value: 0.855923366837272 and parameters: {'max_features': 12513, 'ngram_range': (1, 2), 'C': 0.10333660155465187}. Best is trial 17 with value: 0.855923366837272.
[I 2026-02-02 08:26:00,776] Trial 18 finished with value: 0.8423221101608659 and parameters: {'max_features': 16914, 'ngram_range': (1, 2), 'C': 0.021119880150287408}. Best is trial 17 with value: 0.855923366837272.
[I 2026-02-02 08:26:01,243] Trial 19 finished with value: 0.855923366837272 and parameters: {'max_features': 19935, 'ngram_range': (1, 2), 'C': 0.10412724864982698}. Best is trial 17 with value: 0.855923366837272.
[I 2026-02-02 08:26:01,690] Trial 20 finished with value: 0.8402012327383195 and parameters: {'max_features': 19867, 'ngram_range': (1, 2), 'C': 1.0110293632287644}. Best is trial 17 with value: 0.855923366837272.
[I 2026-02-02 08:26:02,117] Trial 21 finished with value: 0.855267552122214 and parameters: {'max_features': 13101, 'ngram_range': (1, 2), 'C': 0.1536299228499534}. Best is trial 17 with value: 0.855923366837272.
[I 2026-02-02 08:26:02,538] Trial 22 finished with value: 0.849848696602361 and parameters: {'max_features': 13530, 'ngram_range': (1, 2), 'C': 0.047091223894043}. Best is trial 17 with value: 0.855923366837272.
[I 2026-02-02 08:26:02,963] Trial 23 finished with value: 0.857650856445115 and parameters: {'max_features': 17410, 'ngram_range': (1, 2), 'C': 0.117520974511362}. Best is trial 23 with value: 0.857650856445115.
[I 2026-02-02 08:26:03,386] Trial 24 finished with value: 0.840862047704886 and parameters: {'max_features': 19462, 'ngram_range': (1, 2), 'C': 0.01851665381289765}. Best is trial 23 with value: 0.857650856445115.
[I 2026-02-02 08:26:03,810] Trial 25 finished with value: 0.8541826091964501 and parameters: {'max_features': 17122, 'ngram_range': (1, 2), 'C': 0.09556321614614785}. Best is trial 23 with value: 0.857650856445115.
[I 2026-02-02 08:26:04,092] Trial 26 finished with value: 0.8357795968745594 and parameters: {'max_features': 17458, 'ngram_range': (1, 1), 'C': 0.5956510168197423}. Best is trial 23 with value: 0.857650856445115.
[I 2026-02-02 08:26:04,684] Trial 27 finished with value: 0.8298689131646722 and parameters: {'max_features': 18603, 'ngram_range': (1, 2), 'C': 0.006532754761834385}. Best is trial 23 with value: 0.857650856445115.
[I 2026-02-02 08:26:05,132] Trial 28 finished with value: 0.8476430069460632 and parameters: {'max_features': 16920, 'ngram_range': (1, 2), 'C': 0.03621262400582645}. Best is trial 23 with value: 0.857650856445115.
[I 2026-02-02 08:26:05,557] Trial 29 finished with value: 0.8556936264488773 and parameters: {'max_features': 19391, 'ngram_range': (1, 2), 'C': 0.10933375400024939}. Best is trial 23 with value: 0.857650856445115.

## MODEL 3: Naive Bayes

In [153]:

def objective_nb(trial):
    tfidf_max_features = trial.suggest_int("max_features", 5000, 20000)
    ngram_range = trial.suggest_categorical("ngram_range", [(1,1), (1,2)])
    alpha = trial.suggest_float("alpha", 1e-3, 1.0, log=True)

    pipeline = ImbPipeline([
        ("tfidf", TfidfVectorizer( max_features=tfidf_max_features,ngram_range=ngram_range,sublinear_tf=True,min_df=3)),
        ("smote", SMOTE(random_state=42)),
        ("scaler", MaxAbsScaler()), 
        ("clf", MultinomialNB(alpha=alpha))])

    scores = cross_val_score(pipeline,X_train,y_train,cv=cv,scoring="f1_macro")

    return scores.mean()

In [154]:
study_nb = optuna.create_study(direction="maximize")
study_nb.optimize(objective_nb, n_trials=30)

nb_f1 = study_nb.best_value
nb_params = study_nb.best_params

[I 2026-02-02 08:26:19,370] A new study created in memory with name: no-name-641c8696-baff-4265-a933-d6d30a77e35f
[I 2026-02-02 08:26:19,989] Trial 0 finished with value: 0.8366763525711052 and parameters: {'max_features': 6845, 'ngram_range': (1, 2), 'alpha': 0.0033858838984198135}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:20,245] Trial 1 finished with value: 0.7917857609455039 and parameters: {'max_features': 11574, 'ngram_range': (1, 1), 'alpha': 0.3408407260020939}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:20,503] Trial 2 finished with value: 0.7874424013720621 and parameters: {'max_features': 19041, 'ngram_range': (1, 1), 'alpha': 0.022509508289834328}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:20,892] Trial 3 finished with value: 0.8349379768499461 and parameters: {'max_features': 13123, 'ngram_range': (1, 2), 'alpha': 0.103696896501864}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:21,140] Trial 4 finished with value: 0.7913665567982051 and parameters: {'max_features': 16077, 'ngram_range': (1, 1), 'alpha': 0.5013487383158798}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:21,438] Trial 5 finished with value: 0.7851274192433667 and parameters: {'max_features': 19212, 'ngram_range': (1, 1), 'alpha': 0.004944930349903537}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:21,830] Trial 6 finished with value: 0.8341115363169633 and parameters: {'max_features': 8562, 'ngram_range': (1, 2), 'alpha': 0.0744808915523619}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:22,081] Trial 7 finished with value: 0.790154693846913 and parameters: {'max_features': 5806, 'ngram_range': (1, 1), 'alpha': 0.041503873140355536}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:22,333] Trial 8 finished with value: 0.785733858646222 and parameters: {'max_features': 6133, 'ngram_range': (1, 1), 'alpha': 0.0034810897352907538}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:22,766] Trial 9 finished with value: 0.8363171900306294 and parameters: {'max_features': 7356, 'ngram_range': (1, 2), 'alpha': 0.006546848820124965}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:23,203] Trial 10 finished with value: 0.83297943586997 and parameters: {'max_features': 10556, 'ngram_range': (1, 2), 'alpha': 0.0010855990937128856}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:23,609] Trial 11 finished with value: 0.8363171900306294 and parameters: {'max_features': 8409, 'ngram_range': (1, 2), 'alpha': 0.00668360852270866}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:24,005] Trial 12 finished with value: 0.8334685444868881 and parameters: {'max_features': 8973, 'ngram_range': (1, 2), 'alpha': 0.0012735320474231997}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:24,410] Trial 13 finished with value: 0.8356321095848251 and parameters: {'max_features': 5187, 'ngram_range': (1, 2), 'alpha': 0.014200603907794313}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:24,830] Trial 14 finished with value: 0.8360088323543433 and parameters: {'max_features': 13413, 'ngram_range': (1, 2), 'alpha': 0.002717172237969266}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:25,243] Trial 15 finished with value: 0.8359767181568234 and parameters: {'max_features': 7429, 'ngram_range': (1, 2), 'alpha': 0.007965898623224487}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:25,652] Trial 16 finished with value: 0.8356321095848251 and parameters: {'max_features': 10572, 'ngram_range': (1, 2), 'alpha': 0.014398592204479897}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:26,048] Trial 17 finished with value: 0.8345409222010325 and parameters: {'max_features': 14850, 'ngram_range': (1, 2), 'alpha': 0.002237235669175463}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:26,462] Trial 18 finished with value: 0.835491356667655 and parameters: {'max_features': 7016, 'ngram_range': (1, 2), 'alpha': 0.010362766473903691}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:26,888] Trial 19 finished with value: 0.8340816795708305 and parameters: {'max_features': 9746, 'ngram_range': (1, 2), 'alpha': 0.03870168918501248}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:27,299] Trial 20 finished with value: 0.8345409222010325 and parameters: {'max_features': 7250, 'ngram_range': (1, 2), 'alpha': 0.001909838965866487}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:27,739] Trial 21 finished with value: 0.8359845017562753 and parameters: {'max_features': 8131, 'ngram_range': (1, 2), 'alpha': 0.004755110091368991}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:28,135] Trial 22 finished with value: 0.8366661113010135 and parameters: {'max_features': 5005, 'ngram_range': (1, 2), 'alpha': 0.006272186519273442}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:28,590] Trial 23 finished with value: 0.8356321095848251 and parameters: {'max_features': 5286, 'ngram_range': (1, 2), 'alpha': 0.019456561963175915}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:29,014] Trial 24 finished with value: 0.8366763525711052 and parameters: {'max_features': 6612, 'ngram_range': (1, 2), 'alpha': 0.004188435974654447}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:29,435] Trial 25 finished with value: 0.8343770271548203 and parameters: {'max_features': 6508, 'ngram_range': (1, 2), 'alpha': 0.0017459657097617142}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:29,843] Trial 26 finished with value: 0.8366763525711052 and parameters: {'max_features': 5105, 'ngram_range': (1, 2), 'alpha': 0.0032203762099651807}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:30,261] Trial 27 finished with value: 0.8366763525711052 and parameters: {'max_features': 9622, 'ngram_range': (1, 2), 'alpha': 0.0033334590659854324}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:30,667] Trial 28 finished with value: 0.8366763525711052 and parameters: {'max_features': 11800, 'ngram_range': (1, 2), 'alpha': 0.003340408970717869}. Best is trial 0 with value: 0.8366763525711052.
[I 2026-02-02 08:26:30,930] Trial 29 finished with value: 0.7925354390729596 and parameters: {'max_features': 16899, 'ngram_range': (1, 1), 'alpha': 0.11202521594544022}. Best is trial 0 with value: 0.8366763525711052.

## Compare models (CV F1 only)

In [155]:

all_studies = {"Logistic Regression": study_logreg,"Linear SVM": study_svm,"Naive Bayes": study_nb}

results = {"Logistic Regression": study_logreg.best_value,"Linear SVM": study_svm.best_value,"Naive Bayes": study_nb.best_value}

In [156]:
results = {
    "Logistic Regression": logreg_f1,
    "Linear SVM": svm_f1,
    "Naive Bayes": nb_f1}

results

{'Logistic Regression': 0.8549255275653236,
 'Linear SVM': 0.857650856445115,
 'Naive Bayes': 0.8366763525711052}

## Train BEST model on full training data

In [157]:

best_model_name = max(results, key=results.get)
print(f" The winner based on your data is: {best_model_name}")


final_params = all_studies[best_model_name].best_params

if best_model_name == "Linear SVM":
    clf = LinearSVC(C=final_params["C"])
elif best_model_name == "Logistic Regression":
    clf = LogisticRegression(C=final_params["C"], max_iter=1000)
elif best_model_name == "Naive Bayes":
    clf = MultinomialNB(alpha=final_params["alpha"])

steps = [
    ("tfidf", TfidfVectorizer(
        max_features=final_params["max_features"],
        ngram_range=final_params["ngram_range"],
        sublinear_tf=True,
        min_df=3)),
    ("smote", SMOTE(random_state=42))
]
if best_model_name == "Naive Bayes":
    steps.append(("scaler", MaxAbsScaler()))

steps.append(("clf", clf))

best_pipeline = ImbPipeline(steps)
best_pipeline.fit(X_train, y_train)
print("Best pipeline trained successfully!")

 The winner based on your data is: Linear SVM
Best pipeline trained successfully!

## Best model setup for sentiment classification

In [110]:
# Linear SVM was your best performer
best_pipeline = ImbPipeline([
    ("tfidf", TfidfVectorizer(
        max_features=svm_params["max_features"],
        ngram_range=svm_params["ngram_range"],
        sublinear_tf=True,
        min_df=3)),
    ("smote", SMOTE(random_state=42)),
    ("clf", LinearSVC(C=svm_params["C"]))])

best_pipeline.fit(X_train, y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_features=12480, min_df=3,
                                 ngram_range=(1, 2), sublinear_tf=True)),
                ('smote', SMOTE(random_state=42)),
                ('clf', LinearSVC(C=0.2569493393250539))])

## FINAL TEST EVALUATION

In [158]:

y_test_pred = best_pipeline.predict(X_test)

print(classification_report(y_test, y_test_pred))
print("Final Test F1:", f1_score(y_test, y_test_pred))

              precision    recall  f1-score   support

           0       0.76      0.88      0.82       179
           1       0.97      0.93      0.95       740

    accuracy                           0.92       919
   macro avg       0.87      0.91      0.88       919
weighted avg       0.93      0.92      0.92       919

Final Test F1: 0.9511355815554026

### Download Model

In [159]:

joblib.dump(best_pipeline, "sentiment_model.pkl")

['sentiment_model.pkl']

In [160]:
results = {"Logistic Regression": logreg_f1,"Linear SVM": svm_f1,"Naive Bayes": nb_f1}

best_model_name = max(results, key=results.get)
best_cv_f1 = results[best_model_name]

print("Best Model (based on CV F1):", best_model_name)
print("Best Cross-Validated F1:", round(best_cv_f1, 4))

Best Model (based on CV F1): Linear SVM
Best Cross-Validated F1: 0.8577

In [161]:
test_accuracy = accuracy_score(y_test, y_test_pred)
test_f1_macro = f1_score(y_test, y_test_pred, average="macro")
test_f1_positive = f1_score(y_test, y_test_pred) 

print("\nFinal Test Evaluation")
print("---------------------")
print("Selected Model:", best_model_name)
print("Test Accuracy:", round(test_accuracy, 4))
print("Test Macro F1:", round(test_f1_macro, 4))
print("Test Positive-class F1:", round(test_f1_positive, 4))

Final Test Evaluation
---------------------
Selected Model: Linear SVM
Test Accuracy: 0.9227
Test Macro F1: 0.8834
Test Positive-class F1: 0.9511

In [162]:
test_results = X_test.to_frame(name="review")
test_results["actual_sentiment"] = y_test.values
test_results["predicted_sentiment"] = y_test_pred

negative_reviews = test_results[(test_results["actual_sentiment"] == 0) &(test_results["predicted_sentiment"] == 0)]

print("Negative reviews analyzed :", len(negative_reviews))

Negative reviews analyzed : 157

### Top customer pain points from negative reviews

In [164]:
tfidf = TfidfVectorizer(
    max_features=15,
    stop_words="english",
    ngram_range=(1,2))

X_neg = tfidf.fit_transform(negative_reviews["review"])
pain_points = tfidf.get_feature_names_out()

print("Top customer pain points from negative reviews:")
for p in pain_points:
    print("-", p)

Top customer pain points from negative reviews:
- bad
- box
- buy
- dont
- experience
- good
- money
- poor
- product
- purchase
- quality
- qualityread
- shuttle
- waste
- worst